# Generated by Django 4.0.4 on 2022-05-22 08:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='followed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('lfu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lookingforyou')),
            ],
        ),
    ]
